version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: "front-backend:SONAR_TOKEN"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing SonarScanner...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
      - unzip sonar-scanner.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006/bin
build:
  commands:
    - echo Running build...
    - if [ "$RUN_SONAR" = "true" ]; then
        sonar-scanner \
          -Dsonar.projectKey=bmahe1_mahesh \
          -Dsonar.organization=bmahe1 \
          -Dsonar.sources=src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN;
      else
        echo "Sonar scan skipped.";
      fi
  post_build:
    commands:
      - echo Build and scan completed successfully.

artifacts:
  files:
    - '**/*'
