version: 0.2

env:
  variables:
    S3_BUCKET: "new-front-mahesh"  # 🔁 Replace with your actual S3 bucket name
    REGION: "eu-north-1"                    # 🔁 Your AWS region

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building frontend app...
      - npm run build

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync build/ s3://$S3_BUCKET/ --delete
      - echo Deployment complete.

artifacts:
  files:
    - '**/*'
